# Generated by Django 5.1.1 on 2024-11-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=120, verbose_name='Пароль'),
        ),
    ]
