# Generated by Django 5.1.1 on 2024-09-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbackorder',
            name='total_spent_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
